# Generated by Django 4.2 on 2023-12-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='home',
        ),
    ]
